/**
 * Loading a city.
 *
 * The JSON under public/cities is generated by scripts/build-city-data.py from
 * the pipeline's 1 km grid CSVs. It carries each cell's published L_s and the
 * changes the build's neural search found worth making, so the studio opens
 * with real numbers rather than a loading spinner over a search.
 *
 * Cells ship as flat tuples to keep the file small; the fields are positional
 * and the build script writes them in the order `CellTuple` names.
 */

import {
  ZONES,
  type City,
  type CityListing,
  type Proposal,
  type Zone,
} from "./types";

type CellTuple = [
  x: number,
  y: number,
  lat: number,
  lon: number,
  population: number,
  zone: number,
  greenCover: number,
  elevation: number,
  edgeDistance: number,
  livability: number,
  outer: number,
];

interface ProposalPayload {
  cell: string;
  from: number;
  to: number;
  impact: number;
  dL: number;
  people: number;
  cells: number;
  outer: number;
}

interface CityPayload {
  id: string;
  name: string;
  country: string;
  ghslId: string;
  population: number;
  center: [number, number];
  bounds: [[number, number], [number, number]];
  cellSize: [number, number];
  gridSize: [number, number];
  radius: number;
  outerCut: number;
  meanL: number;
  medianL: number;
  cells: CellTuple[];
  proposals: ProposalPayload[];
}

const cache = new Map<string, Promise<City>>();

export function loadCityIndex(): Promise<CityListing[]> {
  return fetch("/cities/index.json")
    .then((r) => {
      if (!r.ok) throw new Error(`City index unavailable (${r.status})`);
      return r.json() as Promise<{ cities: CityListing[] }>;
    })
    .then((d) => d.cities);
}

const proposalCache = new Map<string, Proposal[]>();

/** The changes the build found for a city. Available once `loadCity` resolves. */
export function cityProposals(id: string): Proposal[] {
  return proposalCache.get(id) ?? [];
}

export function loadCity(id: string): Promise<City> {
  const hit = cache.get(id);
  if (hit) return hit;

  const request = fetch(`/cities/${id}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`No grid data for ${id} (${r.status})`);
      return r.json() as Promise<CityPayload>;
    })
    .then(decode)
    .catch((error) => {
      cache.delete(id);
      throw error;
    });

  cache.set(id, request);
  return request;
}

function decode(payload: CityPayload): City {
  // `dist_to_boundary_m` grows toward the city centre, and its scale depends on
  // how big the city is. Normalising against the 75th percentile turns it into
  // a comparable 0-1 "how close to the rim is this" figure, which is what the
  // proposal ordering actually wants.
  const distances = payload.cells.map((c) => c[8]).sort((a, b) => a - b);
  const q75 = distances[Math.floor(distances.length * 0.75)] || 1;

  const cells = payload.cells.map((t) => ({
    id: `${t[0]}:${t[1]}`,
    x: t[0],
    y: t[1],
    lat: t[2],
    lon: t[3],
    population: t[4],
    baseZone: (ZONES[t[5]] ?? "unbuilt") as Zone,
    greenCover: t[6],
    elevation: t[7],
    edgeDistance: t[8],
    edgeness: 1 - Math.min(1, t[8] / q75),
    livability: t[9],
    outer: t[10] === 1,
  }));

  const index = new Map<string, number>();
  cells.forEach((c, i) => index.set(c.id, i));

  proposalCache.set(
    payload.id,
    payload.proposals.map((p, i) => ({
      id: `${payload.id}:${p.cell}:${ZONES[p.to]}`,
      cellId: p.cell,
      from: (ZONES[p.from] ?? "unbuilt") as Zone,
      to: (ZONES[p.to] ?? "unbuilt") as Zone,
      impact: p.impact,
      dL: p.dL,
      people: p.people,
      cells: p.cells,
      outer: p.outer === 1,
      rank: i + 1,
    })),
  );

  return {
    id: payload.id,
    name: payload.name,
    country: payload.country,
    ghslId: payload.ghslId,
    population: payload.population,
    center: payload.center,
    bounds: payload.bounds,
    cellSize: payload.cellSize,
    gridSize: payload.gridSize,
    radius: payload.radius,
    outerCut: payload.outerCut,
    meanLivability: payload.meanL,
    medianLivability: payload.medianL,
    cells,
    index,
  };
}

/** South-west and north-east corners of a single cell. */
export function cellBounds(
  city: City,
  cellIndex: number,
): [[number, number], [number, number]] {
  const cell = city.cells[cellIndex];
  const [dLat, dLon] = city.cellSize;
  return [
    [cell.lat - dLat / 2, cell.lon - dLon / 2],
    [cell.lat + dLat / 2, cell.lon + dLon / 2],
  ];
}

/** The cell containing a point, or null outside the grid. */
export function cellAt(city: City, lat: number, lon: number): number | null {
  const [dLat, dLon] = city.cellSize;
  let best: number | null = null;
  let bestDistance = Infinity;
  for (let i = 0; i < city.cells.length; i += 1) {
    const c = city.cells[i];
    if (Math.abs(c.lat - lat) > dLat / 2 || Math.abs(c.lon - lon) > dLon / 2) continue;
    const d = (c.lat - lat) ** 2 + (c.lon - lon) ** 2;
    if (d < bestDistance) {
      bestDistance = d;
      best = i;
    }
  }
  return best;
}

/**
 * Point-in-cell lookup in constant time.
 *
 * The source grid is regular in Mollweide, not in degrees, so longitude steps
 * widen as you move away from the equator and a cell's grid coordinates cannot
 * be derived from its latitude and longitude arithmetically. Hashing centroids
 * into half-degree-cell buckets sidesteps that: any query point can only fall
 * inside a cell whose centroid sits in one of the nine buckets around it.
 */
export function buildLocator(city: City): (lat: number, lon: number) => number | null {
  const [dLat, dLon] = city.cellSize;
  const buckets = new Map<string, number[]>();

  for (let i = 0; i < city.cells.length; i += 1) {
    const c = city.cells[i];
    const key = `${Math.floor(c.lat / dLat)}:${Math.floor(c.lon / dLon)}`;
    const bucket = buckets.get(key);
    if (bucket) bucket.push(i);
    else buckets.set(key, [i]);
  }

  return (lat, lon) => {
    const by = Math.floor(lat / dLat);
    const bx = Math.floor(lon / dLon);
    let best: number | null = null;
    let bestDistance = Infinity;

    for (let oy = -1; oy <= 1; oy += 1) {
      for (let ox = -1; ox <= 1; ox += 1) {
        const bucket = buckets.get(`${by + oy}:${bx + ox}`);
        if (!bucket) continue;
        for (const i of bucket) {
          const c = city.cells[i];
          if (Math.abs(c.lat - lat) > dLat / 2) continue;
          if (Math.abs(c.lon - lon) > dLon / 2) continue;
          const d = (c.lat - lat) ** 2 + (c.lon - lon) ** 2;
          if (d < bestDistance) {
            bestDistance = d;
            best = i;
          }
        }
      }
    }
    return best;
  };
}
